stages:
 - build
build-docker-image:
 image: docker:stable
 stage: build
 variables:
  IMAGE_TAG: $CI_COMMIT_REF_NAME
  IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
 tags:
  - docker
 services:
  - docker:dind
 script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
  - echo "${IMAGE_NAME}:${IMAGE_TAG} built"
  - docker push ${IMAGE_NAME}:${IMAGE_TAG}
  - echo "${IMAGE_NAME}:${IMAGE_TAG} pushed"
 allow_failure: false
 when: manual